id: P009185
initial_creation_type: ocr
source_metadata:
  id: bdr:W4PD2079
  title: གསུང་འབུམ། བསོད་ནམས་ལྷུན་གྲུབ།
  author: ''
  volumes:
    bd168c363acb483690e0019803706192:
      image_group_id: I4PD2184
      title: ''
      volume_number: 1
      total_pages: 506
    11236182155a447d9092012e6b60de8d:
      image_group_id: I4PD2185
      title: ''
      volume_number: 2
      total_pages: 492
    80eeec5bb6ba4094bb10a3c2acf9d502:
      image_group_id: I4PD2186
      title: ''
      volume_number: 3
      total_pages: 566
