id: IE8330DA0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T18:49:25+00:00'
last_modified: '2022-06-08T09:13:26.453401+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD2079
  title: གསུང་འབུམ། བསོད་ནམས་ལྷུན་གྲུབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D1E3:
      image_group_id: I4PD2184
      title: ''
      total_pages: 506
      order: 1
      base_file: D1E3.txt
    3F2F:
      image_group_id: I4PD2185
      title: ''
      total_pages: 492
      order: 2
      base_file: 3F2F.txt
    '8006':
      image_group_id: I4PD2186
      title: ''
      total_pages: 566
      order: 3
      base_file: 8006.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
